version: '3.8'
services:
  devpostgres:
    container_name: dev_postgres
    image: postgres:14
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .development.env

  testpostgres:
    container_name: test_postgres
    image: postgres:14
    ports:
      - '5433:5432'
    volumes:
      - ./data/postgrestest:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    env_file:
      - .test.env

  rediscontainer:
    container_name: redis-container
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:rediscontainer:6379
    ports:
      - '8081:8081'
    depends_on:
      - rediscontainer
